In [1]:
%load_ext autoreload

%autoreload 2

In [2]:
from dynadojo.baselines.sindy import SINDy
from dynadojo.systems.lds import LDSystem
from dynadojo.systems.lorenz import LorenzSystem
from dynadojo.challenges import FixedComplexity

import pysindy as ps

In [7]:
# challenge = FixedComplexity(N=[1, 50, 500], l=3, e=None, t=50, reps=1, control_horizons=0, max_control_cost_per_dim=0, test_examples=10, test_timesteps=50, system_cls=LorenzSystem, system_kwargs={"noise_scale": 0.01})
challenge = FixedComplexity(N=[5, 10, 50], l=3, e=None, t=50, reps=1, control_horizons=0, max_control_cost_per_dim=0, test_examples=10, test_timesteps=50, system_cls=LDSystem)

In [8]:
smoothed_fd = challenge.evaluate(SINDy, model_kwargs={"differentiation_method": ps.SmoothedFiniteDifference()}, noisy=True, id="smoothed finite diff")
smoothed_fd.head()

rep_id=0, latent_dim=3, embed_dim=3, n=5, t=50, control_h=0, total_cost=0, error=1.5, ood_error=NA,model_seed=4225902070, sys_seed=1482983636
rep_id=0, latent_dim=3, embed_dim=3, n=10, t=50, control_h=0, total_cost=0, error=2.17, ood_error=NA,model_seed=4225902070, sys_seed=1482983636
rep_id=0, latent_dim=3, embed_dim=3, n=50, t=50, control_h=0, total_cost=0, error=1.99, ood_error=NA,model_seed=4225902070, sys_seed=1482983636


rep  latent_dim  embed_dim  timesteps   n     error ood_error  total_cost  \
0    0           3          3         50   5  1.503463      None           0   
1    0           3          3         50  10  2.168407      None           0   
2    0           3          3         50  50  1.989890      None           0   

   duration  system_seed  model_seed                    id  control_horizon  
0  0.099989   1482983636  4225902070  smoothed finite diff                0  
1  0.099879   1482983636  4225902070  smoothed finite diff                0  
2  0.111949   1482983636  4225902070  smoothed finite diff                0

In [146]:
fd = challenge.evaluate(SINDy, model_kwargs={"differentiation_method": ps.FiniteDifference()}, noisy=True, id="finite diff")
fd.head()

[[2.61228446 4.51237042 6.60195328]
 [0.70469211 4.7559205  2.49763064]
 [7.47816324 0.22231653 1.75393256]
 [5.01307378 0.17937021 5.78182767]
 [5.24754059 9.95424573 4.68492285]
 [6.33805028 3.53816949 8.61855757]
 [1.57523718 1.56448998 4.43534625]
 [9.98506288 9.54876853 7.83171116]
 [7.06129452 5.75498625 0.33121074]
 [7.47114464 1.3041739  4.41348301]]
(10, 50, 3)
rep_id=0, latent_dim=3, embed_dim=3, n=1, t=50, control_h=0, total_cost=0, error=5.82e+02, ood_error=NA,model_seed=3100412879, sys_seed=2619540997
[[2.61228446 4.51237042 6.60195328]
 [0.70469211 4.7559205  2.49763064]
 [7.47816324 0.22231653 1.75393256]
 [5.01307378 0.17937021 5.78182767]
 [5.24754059 9.95424573 4.68492285]
 [6.33805028 3.53816949 8.61855757]
 [1.57523718 1.56448998 4.43534625]
 [9.98506288 9.54876853 7.83171116]
 [7.06129452 5.75498625 0.33121074]
 [7.47114464 1.3041739  4.41348301]]
(10, 50, 3)
rep_id=0, latent_dim=3, embed_dim=3, n=50, t=50, control_h=0, total_cost=0, error=2.61e+02, ood_error=NA,mo

rep  latent_dim  embed_dim  timesteps    n       error ood_error  \
0    0           3          3         50    1  581.971017      None   
1    0           3          3         50   50  261.495590      None   
2    0           3          3         50  500  227.280267      None   

   total_cost  duration  system_seed  model_seed           id  control_horizon  
0           0  0.082506   2619540997  3100412879  finite diff                0  
1           0  0.085139   2619540997  3100412879  finite diff                0  
2           0  0.160315   2619540997  3100412879  finite diff                0

In [31]:
tf = challenge.evaluate(SINDy, model_kwargs={"differentiation_method": ps.SINDyDerivative(kind='trend_filtered', order=0, alpha=1e-2)}, noisy=True, id="trend filtered")
tf.head()

rep  n  latent_dim  embed_dim  timesteps  control_horizons       loss   
0    0  1           3          3         50                 0  17.952157  \

   total_cost              id  
0           0  trend filtered

In [32]:
spline = challenge.evaluate(SINDy, model_kwargs={"differentiation_method": ps.SINDyDerivative(kind='spline', s=1e-2)}, noisy=True, id="spline")
spline.head()

rep  n  latent_dim  embed_dim  timesteps  control_horizons      loss   
0    0  1           3          3         50                 0  0.628707  \

   total_cost      id  
0           0  spline